# Generated by Django 4.1.4 on 2022-12-12 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hudud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuman', models.CharField(max_length=250)),
                ('viloyat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='agri.hudud')),
            ],
        ),
        migrations.CreateModel(
            name='AgriSelect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agri', models.CharField(max_length=250)),
                ('chorva', models.CharField(max_length=250)),
                ('yer', models.IntegerField()),
                ('mahsulot_name', models.CharField(max_length=250)),
                ('mahsulot_soni', models.IntegerField()),
                ('shartnoma', models.CharField(max_length=250)),
                ('ekspert', models.IntegerField()),
                ('bozorga_chaqirishi', models.IntegerField()),
                ('tuman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='agri.tuman')),
            ],
        ),
    ]
